# Generated by Django 2.1.5 on 2019-03-03 19:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('preço', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('embalagem', models.CharField(blank='true', default='NA', max_length=200)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.AddField(
            model_name='lista',
            name='items',
            field=models.ManyToManyField(related_name='list_of_items', through='mercado_app.Items', to='mercado_app.Produto'),
        ),
        migrations.AddField(
            model_name='lista',
            name='mercado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado_app.Mercado'),
        ),
        migrations.AddField(
            model_name='items',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_to_lista', to='mercado_app.Lista'),
        ),
        migrations.AddField(
            model_name='items',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado_app.Produto'),
        ),
    ]
