# Generated by Django 2.1.5 on 2019-02-07 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('preço', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('local', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descrição', models.CharField(blank=True, max_length=200)),
                ('seção', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='lista',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado_app.Produto'),
        ),
        migrations.AddField(
            model_name='lista',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercado_app.Loja'),
        ),
    ]
